name: .NET

on:
  push:
    branches: [ rebuild-ir-ort ]
  pull_request:
    branches: [ rebuild-ir-ort ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04] #,windows-2019,macos-10.15]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        
      - name: Build
        run: dotnet build

      - name: Test
        run: |
          dotnet test --no-build --verbosity normal 